# -- stackhawk configuration for MyIPA --
app:
  # -- An applicationId obtained from the StackHawk platform. --
  applicationId: b18547ad-a57b-4c46-ae48-3801dd1ee4ca # (required)
  # -- The environment for the applicationId defined in the StackHawk platform. --
  env: Development # (required)
  # -- The url of your application to scan --
  host: https://kutsevmaxim-svelte-work-time-tracker-71a2.twc1.net # (required)


# -- Customized Configuration for GraphQL/SOAP/OpenAPI, add here --
  # Configuration Docs: https://docs.stackhawk.com/hawkscan/configuration/

# -- If Authenticated Scanning is needed, add here --
  # Authenticated Scanning Docs: https://docs.stackhawk.com/hawkscan/authenticated-scanning.html
  # Authenticated Scanning Repo: https://github.com/kaakaww/scan-configuration/tree/main/Authentication

# -- Help Section --
  # Docs: https://docs.stackhawk.com/
  # Contact Support: support@stackhawk.com